### ISSUE TITLE
Conversion ended in 404 error

### ISSUE THREAD

**Issue by peterkirs** [c3mdigital/media-tools-for-WordPress#2]
The conversion for the following HTML code ended in a 404 error:

<a href="http://1.bp.blogspot.com/-VdqNYzWXR68/T-A3SyCjd_I/AAAAAAAAQIY/DL5yPyk2d7c/s1600/PEW%2BEuro%2B1.png" target="_blank"><img src="http://backup.snbchf.com/wp-content/uploads/2012/08/PEW%2BEuro%2B11.png" alt="" width="400" height="268" border="0" /></a>

The old image still works:
http://1.bp.blogspot.com/-VdqNYzWXR68/T-A3SyCjd_I/AAAAAAAAQIY/DL5yPyk2d7c/s1600/PEW%2BEuro%2B1.png

The new one leads to 404:
http://backup.snbchf.com/wp-content/uploads/2012/08/PEW%2BEuro%2B11.png

**Comment by peterkirs** [comment]
I supposed that these images might be jpg and did the following.
1) restore the old version containing only the old images
http://backup.snbchf.com/2012/07/six-reasons-why-italy-may-exit-the-euro-before-spain-ultimate-occupy-movement/

2) rename the old links to .jpg like follows:
<a href="http://1.bp.blogspot.com/-VdqNYzWXR68/T-A3SyCjd_I/AAAAAAAAQIY/DL5yPyk2d7c/s1600/PEW%2BEuro%2B1.jpg" target="_blank"><img style="border-style: initial; border-color: initial; border-width: 0px;" src="http://1.bp.blogspot.com/-VdqNYzWXR68/T-A3SyCjd_I/AAAAAAAAQIY/DL5yPyk2d7c/s1600/PEW%2BEuro%2B1.jpg" alt="" border="0" /></a>

3) delete the already imported new media for this post

4) rerun media tools

--> Media Tools does not log the treatment of the post anymore.
But it imports the images, unfortunately as PNG, even if the links are JPG.
Result: http://backup.snbchf.com/wp-content/uploads/2012/08/Media-Tools.png

**Comment by c3mdigital** [comment]
The reason your getting 404 errors on the urls with the % symbols is because they are blocked by the Apache mod_security rules your host is running.  You should be able to open a support ticket with them to have your domain whitelisted.

**Comment by peterkirs** [comment]
Is this really the Apache host or maybe WP Better Security plugin ?

**Comment by peterkirs** [comment]
By the way, it looks that the source where we got the data from, is protecting its images

**Comment by c3mdigital** [comment]
mod_security is a very complex module that allows for custom rules.  Host Gator uses a very strict set of defined rules.  See this thread for more info:  http://forums.hostgator.com/frustrating-403-error-t48309.html?amp;
