### ISSUE TITLE
External image not imported

### ISSUE THREAD

**Issue by peterkirs** [c3mdigital/media-tools-for-WordPress#4]
The following external image did not get imported:

<div><span style="font-size: medium;"><span style="line-height: 24px;"><a href="http://www.lighthouseinvestmentmanagement.com/wp-content/uploads/2012/08/US-debt-by-sector.png"><img class="aligncenter size-full wp-image-1249" title="US debt by sector" src="http://www.lighthouseinvestmentmanagement.com/wp-content/uploads/2012/08/US-debt-by-sector-e1345155526234.png" alt="" width="675" height="493" /></a></span></span></div>

When you open the image directly, it says permission denied.
Interestingly I can view the image inside the WP blog without problems.
http://snbchf.com/2012/09/the-beautiful-deleveraging/

**Comment by c3mdigital** [comment]
403 Permission denied errors are not this plugin.  It makes a simple http browser request just like if you typed in the url directly. 

http://www.lighthouseinvestmentmanagement.com/wp-content/uploads/2012/08/US-debt-by-sector-e1345155526234.png
